INSERT INTO PUBLIC.AUTHORS ( NAME) VALUES ( 'Mark Twain');
INSERT INTO PUBLIC.AUTHORS ( NAME) VALUES ( 'Andjey Sapkovski');
INSERT INTO PUBLIC.AUTHORS ( NAME) VALUES ( 'George Martin');
INSERT INTO PUBLIC.AUTHORS ( NAME) VALUES ( 'James Orwell');

INSERT INTO PUBLIC.GENRES ( NAME) VALUES ( 'Drama');
INSERT INTO PUBLIC.GENRES ( NAME) VALUES ( 'Fantasy');

INSERT INTO PUBLIC.BOOKS ( TITLE, AUTHOR_ID, GENRE_ID) VALUES ( 'Tom Soyer', 1, 1);
INSERT INTO PUBLIC.BOOKS ( TITLE, AUTHOR_ID, GENRE_ID) VALUES ( 'Witcher', 2, 2);
INSERT INTO PUBLIC.BOOKS ( TITLE, AUTHOR_ID, GENRE_ID) VALUES ( 'Game of Thrones', 3, 2);
INSERT INTO PUBLIC.BOOKS ( TITLE, AUTHOR_ID, GENRE_ID) VALUES ( '1984', 4, 1);
